# Generated by Django 4.2.4 on 2023-08-21 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Shop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_title', models.CharField(max_length=20)),
                ('product_price', models.IntegerField()),
                ('product_size', models.CharField(choices=[('small', 'small'), ('meduiem', 'meduiem'), ('large', 'large')], max_length=10)),
                ('product_color', models.CharField(choices=[('red', 'red'), ('green', 'green'), ('blue', 'blue'), ('purple', 'purple')], max_length=10)),
                ('categories', models.CharField(choices=[('men', 'men'), ('women', 'women'), ('children', 'children')], max_length=10)),
            ],
        ),
    ]
