# Generated by Django 4.2.4 on 2023-08-24 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_shop_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='product_description',
            field=models.TextField(default='', max_length=1000),
            preserve_default=False,
        ),
    ]
