# Generated by Django 4.2.4 on 2023-08-30 02:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0010_shop_vendor_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shop',
            old_name='product_title',
            new_name='product_name',
        ),
    ]
