# Generated by Django 4.2.4 on 2023-08-31 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0011_rename_product_title_shop_product_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='VendorAdd',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('add_prod_name', models.CharField(max_length=20)),
                ('vendor_name', models.CharField(max_length=20)),
                ('vendor_email', models.EmailField(max_length=254)),
            ],
        ),
    ]
