# Generated by Django 4.2.4 on 2023-08-31 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0012_vendoradd'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vendoradd',
            old_name='vendor_name',
            new_name='company_name',
        ),
        migrations.AddField(
            model_name='vendoradd',
            name='product_description',
            field=models.TextField(default='', max_length=1000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vendoradd',
            name='product_images',
            field=models.ImageField(default=1, upload_to='vendor_images/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vendoradd',
            name='product_price',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
