# Generated by Django 4.2.4 on 2023-09-01 00:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0013_rename_vendor_name_vendoradd_company_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendoradd',
            name='product_categ',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='prod_categ', to='shop.shop'),
            preserve_default=False,
        ),
    ]
