# Generated by Django 4.2.4 on 2023-09-01 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0015_alter_vendoradd_product_categ'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendoradd',
            name='published_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
