# Generated by Django 4.2.4 on 2023-09-01 00:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0016_vendoradd_published_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vendoradd',
            old_name='published_at',
            new_name='created_at',
        ),
    ]
